# settings.yaml
# box_name: "sloopstash/ubuntu-22-04"
box_name: "bento/ubuntu-22.04"
# box_version: "2.1.1"
vm:
- name: "controlplane"
  ip: "192.168.201.10"
  memory: "4096"
  cpus: "4"
- name: "server"
  ip: "192.168.201.11"
  memory: "4096"
  cpus: "4"
- name: "agent"
  ip: "192.168.201.12"
  memory: "4096"
  cpus: "4"

